//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.30 at 01:25:28 AM ICT 
//

package beans;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for product complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ProductName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SupplierID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="CategoryID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="QuantityPerUnit">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UnitPrice">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="12"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UnitsInStock" type="{}smallint"/>
 *         &lt;element name="UnitsOnOrder" type="{}smallint"/>
 *         &lt;element name="ReorderLevel" type="{}smallint"/>
 *         &lt;element name="Discontinued" type="{}discontinued"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product", propOrder = { "productID", "productName",
		"supplierID", "categoryID", "quantityPerUnit", "unitPrice",
		"unitsInStock", "unitsOnOrder", "reorderLevel", "discontinued" })
public class Product implements Serializable {

	@XmlElement(name = "ProductID", required = true)
	protected BigInteger productID;
	@XmlElement(name = "ProductName", required = true)
	protected String productName;
	@XmlElement(name = "SupplierID", required = true, nillable = true)
	protected BigInteger supplierID;
	@XmlElement(name = "CategoryID", required = true, nillable = true)
	protected BigInteger categoryID;
	@XmlElement(name = "QuantityPerUnit", required = true, nillable = true)
	protected String quantityPerUnit;
	@XmlElement(name = "UnitPrice", required = true, defaultValue = "0.00", nillable = true)
	protected BigDecimal unitPrice;
	@XmlElement(name = "UnitsInStock", required = true, type = Integer.class, defaultValue = "0", nillable = true)
	protected Integer unitsInStock;
	@XmlElement(name = "UnitsOnOrder", required = true, type = Integer.class, defaultValue = "0", nillable = true)
	protected Integer unitsOnOrder;
	@XmlElement(name = "ReorderLevel", required = true, type = Integer.class, defaultValue = "0", nillable = true)
	protected Integer reorderLevel;
	@XmlElement(name = "Discontinued", required = true, defaultValue = "0")
	protected BigInteger discontinued;

	public Product() {

	}

	/**
	 * Gets the value of the productID property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getProductID() {
		return productID;
	}

	/**
	 * Sets the value of the productID property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setProductID(BigInteger value) {
		this.productID = value;
	}

	/**
	 * Gets the value of the productName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * Sets the value of the productName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProductName(String value) {
		this.productName = value;
	}

	/**
	 * Gets the value of the supplierID property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSupplierID() {
		return supplierID;
	}

	/**
	 * Sets the value of the supplierID property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setSupplierID(BigInteger value) {
		this.supplierID = value;
	}
	
	

	/**
	 * Gets the value of the categoryID property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getCategoryID() {
		return categoryID;
	}

	/**
	 * Sets the value of the categoryID property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setCategoryID(BigInteger value) {
		this.categoryID = value;
	}

	/**
	 * Gets the value of the quantityPerUnit property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQuantityPerUnit() {
		return quantityPerUnit;
	}

	/**
	 * Sets the value of the quantityPerUnit property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setQuantityPerUnit(String value) {
		this.quantityPerUnit = value;
	}

	/**
	 * Gets the value of the unitPrice property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getUnitPrice() {
		return unitPrice;
	}

	/**
	 * Sets the value of the unitPrice property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setUnitPrice(BigDecimal value) {
		this.unitPrice = value;
	}

	/**
	 * Gets the value of the unitsInStock property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getUnitsInStock() {
		return unitsInStock;
	}

	/**
	 * Sets the value of the unitsInStock property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setUnitsInStock(Integer value) {
		this.unitsInStock = value;
	}

	/**
	 * Gets the value of the unitsOnOrder property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getUnitsOnOrder() {
		return unitsOnOrder;
	}

	/**
	 * Sets the value of the unitsOnOrder property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setUnitsOnOrder(Integer value) {
		this.unitsOnOrder = value;
	}

	/**
	 * Gets the value of the reorderLevel property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getReorderLevel() {
		return reorderLevel;
	}

	/**
	 * Sets the value of the reorderLevel property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setReorderLevel(Integer value) {
		this.reorderLevel = value;
	}

	/**
	 * Gets the value of the discontinued property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getDiscontinued() {
		return discontinued;
	}

	/**
	 * Sets the value of the discontinued property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setDiscontinued(BigInteger value) {
		this.discontinued = value;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null || obj.getClass() != getClass()) {
			return false;
		}
		Product product = (Product) obj;
		if (this.productID.equals(product.productID)) {
			return true;
		}
		return false;
	}

	@Override
	public int hashCode() {
		int hash = 5;
		hash = 47 * hash
				+ (this.productID != null ? this.productID.hashCode() : 0);
		return hash;
	}

	public boolean isValidate() {
		if (this.productName == null
				|| this.productName.equals("")
				|| this.supplierID == null
				|| this.supplierID.equals("")
				|| this.supplierID == null
				|| this.supplierID.equals("")
				|| this.supplierID == null
				|| this.supplierID.equals("")
				|| (this.quantityPerUnit != null && this.quantityPerUnit
						.length() > 20)
				|| (this.unitPrice != null && !this.unitPrice
						.toString()
						.matches(
								"\\+?0*((\\d{0,12}\\.?0{0,2})|(\\d{0,11}\\.?\\d{0,1})|(\\d{0,10}\\.?\\d{0,2}))"))) {
			return false;
		}
		return true;
	}
}
